### ISSUE TITLE
Pretty please (Mirek)

### ISSUE THREAD

**Issue by rosskukulinski** [mirumee/overv.io-beta#105]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

Hello!  Found this via [this blog post](http://www.ianbicking.org/blog/2014/03/use-github-issues-to-organize-a-project.html) that Mirek commented on.

We're currently evaluating a handful of these types of platforms and would love to giver overv.io a try.

Thanks!
-Ross

**Comment by mirekm** [comment]
Sorry for a late response Ros. We're still sorting out some problems preventing us from releasing more invitations but we should be ready to give away more beginning of the next week.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
