### ISSUE TITLE
Create workspace modal has invisible text inputs in Firefox

### ISSUE THREAD

**Issue by fmr** [mirumee/overv.io-beta#11]
I'm able to create new workspaces, I just can't see what I'm typing inside the text inputs:

![screen shot 2014-02-20 at 10 12 45 pm](https://f.cloud.github.com/assets/592174/2217645/4e3cd4ba-9a20-11e3-846c-c61fa5d1c887.png)

OS: OS X Mavericks (10.9.1)
Browser: Mozilla Firefox 27.0.1

Here's what it looks like in Chrome:

![screen shot 2014-02-20 at 10 17 33 pm](https://f.cloud.github.com/assets/592174/2217665/a9ba8166-9a20-11e3-9193-25c20c09308b.png)

**Comment by mirekm** [comment]
Thanks! Firefox hasn't been addressed properly yet so the feedback will be very helpful.
