### ISSUE TITLE
OHAI? Can I try?

### ISSUE THREAD

**Issue by joelglovier** [mirumee/overv.io-beta#13]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

I'm a GitHubber, but am requesting access from my test account, instead of my Hubber account (@jglovier) for security reasons. Gracias. :smile: :octocat: :heart: 

BTW, clever work on your product landing page! Both design :lipstick: and copy :pencil2:  is really fun. :zap:

**Comment by mirekm** [comment]
Holy :zap: moly :exclamation:, a God has spoken to us! :innocent: 
:fearful: Alright! You got it Joel, just put your helmet and safety googles on, try to stick to Chrome for now and you should be good to go.

We really hope you'll like it: https://overv.io/login/

PS: Thanks for the kind words!

**Comment by patrys** [comment]
```
Oh Lord, please don't burn us,
Don't grill or toast your flock,
Don't put us on the barbecue,
Or simmer us in stock,
Don't braise or bake or boil us,
Or stir-fry us in a wok...

Oh please don't lightly poach us,
Or baste us with hot fat,
Don't fricassee or roast us,
Or boil us in a vat,
And please don't stick thy servants Lord,
In a Rotissomat...
```

**Comment by joelglovier** [comment]
LOL, thanks guys. No "God" here, just a humble Hubber. I haz no judgement to render, just interested to check out your hard work. :wink:

**Comment by joelglovier** [comment]
Some quick feedback on my initial impressions.

### Blank slate view

![image](https://f.cloud.github.com/assets/5043477/2220323/42c75ad4-9a4c-11e3-8002-353d95e78197.png)

The blank slate view shows as the most prominent action, + for adding a Workspace. However, when I click that to create a new workspace, I'm not allowed since apparently I don't have any repositories to connect to it yet. Perhaps, if repos are a requirement for Workspaces, adding a Repository should be the first suggested action instead?

![image](https://f.cloud.github.com/assets/5043477/2220328/5ec4ef94-9a4c-11e3-8e2e-3a32b9af17d5.png)

And, if you attempt to open the Create Workspace dialog without any added repositories yet, there could be an alert at the top that says something like _"Oops! You don't have any repositories to create a workspace from yet. [Add a repository](#) first so you can create a new workspace with it."_

Or, instead of that approach you could could add an "Add a new repository" option to the "Select repositories" field where users could simply add a new one there.

### Adding repositories

![image](https://f.cloud.github.com/assets/5043477/2220439/b2cb8bf6-9a4d-11e3-9764-661b72d4f70d.png)

When I finally found the add repository dialog, I was surprised to see none of my repos have been imported already, or are available to select. It appears I need to manually type it in, which would just lead me back to GitHub, where if I was just exploring this app for the first time I might get tired of exploring and stay at GitHub. Anything you do to send users away from your app is going to risk having them never come back.

I'm not sure if that's default behavior, or if it has to do with limitations because I'm using my test GitHub account (I do have repos, so I'm not sure why it didn't list them).

Anyhow, as much as you can do to keep your users within the app is going to encourage them to stick with it through the "learning how it works" phase.

Another suggestion is that you could use a utility like [Joyride](http://zurb.com/playground/jquery-joyride-feature-tour-plugin) or [Hopscotch](https://github.com/linkedin/hopscotch) to create a tutorial experience for the first few steps for new users.

Anyway looks nice so far. Just thought I'd share some of my initial impressions. I'll be sure to leave any further feedback here.

Thanks again!

**Comment by mirekm** [comment]
Thanks a lot Joel, great feedback.

True, blank slate view requires dedicated time and effort. A tour or some other explanation of how, why, what and where is planned to be there in Public Beta. Nonetheless, no doubt it would be better to have it there in some form already.

# Workspaces & repositories

I totally agree. We lean towards having the ability of adding new repositories in both _New workspace_ modal as well as inside the _Workspace_ view itself (_New column_ form). We're still thinking about the details but I hope to have this change implemented soon. The current tab and especially the input definitely needs improvements: auto-complete with all the repos is a minimum.

Thanks again for the feedback and your patience!

**Comment by jglovier** [comment]
Awesome - glad to hear it's in the works. Can't wait to see how everything shapes up for the public beta! :zap:

**Comment by jglovier** [comment]
![support](http://gifs.joelglovier.com/support/Sean-Connery-Fist-Pump-US-Open.gif)

**Comment by mirekm** [comment]
Hey Joel,

It's been a while but I wonder what you think about the new splash and our current design (https://overv.io). Despite there's a number of things we still need to put more UX (and design) work in the app is finally in public beta. 🐌 

Kind regards!
Mirek
