### ISSUE TITLE
Please, sir, please, may I have the beta? (Original poem :)

### ISSUE THREAD

**Issue by lachlanjc** [mirumee/overv.io-beta#140]
Please.
My life is just a useless one.
I can’t make progress,
my team just can’t work together.
The GitHub Issues spiral out of control.
My fate, which I’m fast approaching,
is a lonely series of dead side projects.
A sad and sorry story
of painful repo’s that are no more.

The only hope I have
is you. You!
You’ll solve all this,
you amazing people.
You’ll fix my problems,
you amazing people.
You’ll liven up my GitHub,
you amazing people.

So please, sir,
may I have the beta?
My fate will otherwise meet me soon.
Too soon, in fact.
So soon, in fact,
that my GitHub may die a lonely death.
And that would be just sad, because it would be one
that could have been rescued with the use of the amazing Overv.io Beta.

**Comment by bogomil** [comment]
I love it :)

**Comment by lachlanjc** [comment]
Haha, thanks @bogomil. When do you think the beta will be ready?

**Comment by bogomil** [comment]
Dunno :) I am interested too. @lachlanjc - also feel free to browse some more Issues upgrades: https://medium.com/@bogomep/three-ways-to-turn-your-github-issues-into-a-real-boy-aa16217a4977

**Comment by mirekm** [comment]
We love it @lachlanjc! :)
Promise to give more invitations away any day now.

**Comment by lachlanjc** [comment]
@kirekm :+1:

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
