### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by nafisto** [mirumee/overv.io-beta#149]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

![download](https://cloud.githubusercontent.com/assets/1227046/3828584/e4c72e54-1d78-11e4-965c-7643f6428463.jpeg)

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
