### ISSUE TITLE
Pretty please: This is my workspace...

### ISSUE THREAD

**Issue by stefanfoulis** [mirumee/overv.io-beta#15]
This is my workspace. There are many others like it, but this one is mine. My workspace is my best friend. It is my life. I must master it as I must master my life. Without me, my workspace is useless. Without my workspace, I am useless. I must master my workspace true. I must write tests that reveal the bugs, who are trying to kill me. I must find them before the customer does. I will. Before God I swear this creed: my workspace and myself are defenders of code quality, we are the masters of our enemy, we are the saviors of my life. So be it, until there are no bugs, but features. Amen.

**Comment by mirekm** [comment]
You're in :) https://overv.io/login/
