### ISSUE TITLE
Pretty pretty please with cherries and whatnot on top?

### ISSUE THREAD

**Issue by jeremybell** [mirumee/overv.io-beta#150]
Hahahaha... love this signup process. Perfect.

Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

**Comment by jeremybell** [comment]
I'd love the opportunity to try this out, and will be more than vocal with any bugs or feature ideas that present themselves. I was previously a partner at Teehan+Lax, so I've got a fair bit of experience designing and critiquing great user experiences. 

I've managed to spend the afternoon reviewing a bunch of solutions for our team. We're currently using Waffle.io on top of GitHub issues, and this looks to be a (hopefully) superior solution. We were previously using Huboard, which I wasn't a huge fan for a number of reasons. I've investigated everything from JIRA to Basecamp, and what we really want is something that allows the developers to use the tools they're comfortable with (ie GitHub) while providing management with some macro perspective on the project as a whole.

Either way, I'm very excited to see what Overv.io has to offer.

**Comment by mirekm** [comment]
Thanks for applying Jeremy. We will be more than happy to invite you to our Private Beta however we wont be ready to send the new invitations earlier than the beginning of the next week.

I hope you're ready for this bumpy ride since many features are just still in the air or require more attention. Nonetheless, I can't wait for your feedback. Will keep you posted. Expect the invitation soon.

**Comment by jeremybell** [comment]
That's fantastic. I have my crash helmet and look forward to the ride.

**Comment by jeremybell** [comment]
Hey guys - just wanted to checkin and see how it's going... any word on the private beta?

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
