### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by IyadAssaf** [mirumee/overv.io-beta#152]
Please recognise (UK spelling) my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

Also, here is a picture of a puppy:
![](http://www.clickerzoneuk.co.uk/cz/wp-content/uploads/2010/10/PuppySmall.jpg)

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
