### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by zsup** [mirumee/overv.io-beta#172]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

We run a big open source project in the Internet of Things, and have been desperately seeking the right tool that helps us manage our work internally (when some repositories are open and others are closed) and also gives our community visibility into what we're working on. I'm hoping overv.io does that for us!

**Comment by zsup** [comment]
Oh, and here we are:

http://www.github.com/spark

**Comment by mirekm** [comment]
That's great Zach. I will glad to invite you as soon as we're able early next week. We would be very interested in your feedback. Thanks for applying!

**Comment by zsup** [comment]
:+1:

**Comment by zsup** [comment]
Hey guys, what's the word on this? Would love to test this out.

**Comment by mirekm** [comment]
I'm sorry it took that long but here you go!

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
