### ISSUE TITLE
For what it's worth

### ISSUE THREAD

**Issue by kentquirk** [mirumee/overv.io-beta#178]
I lead a team of developers in a nonprofit, opensource, [medical startup](http://tidepool.org) working on [many GH repos](https://github.com/tidepool-org) simultaneously. Looks like you're solving a problem we have.

So... please find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

**Comment by mirekm** [comment]
Will be able to share more invitations on the beginning of the next week. Judging by your description we would be very interested in your feedback!

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
