### ISSUE TITLE
Hark O Dear Brother or Sister!

### ISSUE THREAD

**Issue by brettwise** [mirumee/overv.io-beta#186]
Hark o dear brother or sister. 
Feel my pain.
The thing that's become by bain.
Many a quid have I paid in a bid to the doctors who prescribe hugs and drugs to rid me of these bugs.

But none of them have worked.
They've only lurked and irked and made me shirk.

O. O how I need something to track these dastardly bugs.
There's something. 
Something I heard. 
A solution someone told me about. 
A solution that rhymes with a brazilian town known for it's christ and a character from star trek. 
Rio Data you say? WTF.
Hmmm. Rio Data....
Ooooo, I know! The overvio beta.

**Comment by mirekm** [comment]
Another genius request! Thanks for applying and expect your invitation as soon as we start giving them away again (most certainly the beginning of the next week). Class!

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
