### ISSUE TITLE
Pretty please let me try :)

### ISSUE THREAD

**Issue by rickharrison** [mirumee/overv.io-beta#195]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

Also, I'm starting a new company and we are still trying to figure out our workflow. We keep tending to come back to GitHub so a tool to help us with this would be great!

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
