### ISSUE TITLE
Pretty please, could i try out overv.io?

### ISSUE THREAD

**Issue by kayvz** [mirumee/overv.io-beta#202]
Your splash page is pretty cheeky. I like it a lot. Also I like that your beta access form is a Github issue. Less cheeky, but clever. And sensible. And dog-foody. I'm a fan, and I think i'd be even more of a fan if I tried yo' product. I'd be very appreciative for an invite! I'll also wash dishes.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
