### ISSUE TITLE
Please add me to the beta (this sounds interesting)

### ISSUE THREAD

**Issue by nathanpalmer** [mirumee/overv.io-beta#206]
I appreciate the fact that you pre-filled out the form for me. I'm going to add in a little more context. We don't use GitHub issues today because we work in a Kanban'ish way. I'm interested to see what this offers beyond what GitHub gives already.

Also, we're on private repos.

Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
