### ISSUE TITLE
Pretty please consider our team

### ISSUE THREAD

**Issue by genevate** [mirumee/overv.io-beta#217]
Have a small team that can give you great feedback on the product. Please please find me and our team worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day. Thanks.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
