### ISSUE TITLE
Pretty please - no really.

### ISSUE THREAD

**Issue by phillbaker** [mirumee/overv.io-beta#236]
Please recognize my effort that consists mostly of filling this form (and hitting the submit button!) and find me worthy of joining the private beta. I hereby offer my semi-solemn vow to file some of the issues I encounter, consider sharing my experience when asked to and give people hugs the rest of the day.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
