### ISSUE TITLE
We have GitHub flow in our project, but need some mangement tool

### ISSUE THREAD

**Issue by pftg** [mirumee/overv.io-beta#256]
All our projects has github flow, but for some projects with a lot of ideas and features which will be implemented per iterations, so GitHub milestones is not enough to plan our day, week and months issues, also we would like to see epoch too.

I'd like to review your stuff and to try to use on real comerce projects.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
