### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by heptat** [mirumee/overv.io-beta#27]
Oh...I think I already sent this? What's happening with it? Btw, do you have velocity?

**Comment by mirekm** [comment]
Hold on guys! We're releasing the second batch of invitations this week.

**Comment by heptat** [comment]
Holding! :stuck_out_tongue_winking_eye:

**Comment by mirekm** [comment]
:snail:
Thanks for the patience! 
You're good to go https://overv.io/login/
