### ISSUE TITLE
Pretty please wanna try it out

### ISSUE THREAD

**Issue by mose** [mirumee/overv.io-beta#273]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

Well, this is quite well said. I could not have said it better. Oh. I just did. Ah no that was a template. Damn guys you are good.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
