### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by lukefx** [mirumee/overv.io-beta#282]
Good times for a change
see, the luck I've had
can make a good man
turn bad

So please please please
let me, let me, let me
let me get what I want
this time

Haven't had a dream in a long time
see, the life I've had
can make a good man bad

So for once in my life
let me get what I want
Lord knows it would be the first time
Lord knows it would be the first time

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
