### ISSUE TITLE
Unable to create a workspace

### ISSUE THREAD

**Issue by rosskukulinski** [mirumee/overv.io-beta#325]
Trying to create a workspace, but the save button appears to be disabled.
![screen shot 2014-09-16 at 6 06 02 pm](https://cloud.githubusercontent.com/assets/2746479/4297190/dca818e2-3e06-11e4-8645-3368e86fac0f.png)

**Comment by mirekm** [comment]
Thanks for a feedback Ross.

This form definitely deserves a second look. Actually «Name the workspace» is a placeholder that needs to be replaced with a unique name of the workspace. _Description_ field below feels redundant and we will most likely get rid of it shortly.

Bottom line is that the _Save_ button remains disabled as long as the form is not valid (no name provided in this case).

**Comment by rosskukulinski** [comment]
Ahh, I got it now. Thanks.
