### ISSUE TITLE
This looks friggin' perfect (Private beta request)

### ISSUE THREAD

**Issue by ajb** [mirumee/overv.io-beta#328]
> Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

We at @dobtco have been waiting for something like this for a long time.

**Comment by mirekm** [comment]
Thanks for applying Adam. Hopefully our beta can address at least some of your everyday  headaches. Any feedback is highly appreciated — especially regarding possible features/changes supporting small and medium teams problems and better project management!

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
