### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by ingebretsen** [mirumee/overv.io-beta#333]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

If I like it, I may also: 1) tell my close friends and associates about it and 2) send you a mix CD.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
