### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by avinasha** [mirumee/overv.io-beta#338]
Haha! 

Nice way of accepting beta invites! I already love you guys. We SupportBee use Github issues for project management. We use Trello to manage a high perspective of whats happening. Your product might help us. I would love to give it a try.

Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
