### ISSUE TITLE
Using plane crash terminology in email is badly timed

### ISSUE THREAD

**Issue by codeinthehole** [mirumee/overv.io-beta#34]
Best not to remind people of a mysterious tragic event in the Indian ocean.

**Comment by mirekm** [comment]
Thanks for pointing this out David. Totally unintended and actually written long before the tragic flight. Bad timing indeed — we should start spending more time outside of the office and text editors I guess.

**Comment by mirekm** [comment]
I case you want to give it a go I white-listed you David: https://overv.io/login/

**Comment by codeinthehole** [comment]
Cheers
