### ISSUE TITLE
Pretty please (Ron Burgundy-style)

### ISSUE THREAD

**Issue by ITSoFRISCHial** [mirumee/overv.io-beta#361]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

This is how I will feel using this tool with my engineers:
![image](https://cloud.githubusercontent.com/assets/3266084/4971152/ee9da872-6891-11e4-8f11-5d3c9ea94713.png)

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
