### ISSUE TITLE
Remember Harvest project and task

### ISSUE THREAD

**Issue by timanrebel** [mirumee/overv.io-beta#362]
When I'm fixing lots of small bugs, it gets really annoying that I have to enter the Harvest project and task overtime. Could over.io remember the last project and task that I have selected? So I can still edit it, but can just click start when it stayed the same?

**Comment by mirekm** [comment]
Thanks Timan, great feedback again. At the moment it's only remembered per issue. I agree, the project and task should be also initialized to the last selected settings within a workspace.

**Comment by mirekm** [comment]
Ready for testing.

**Comment by timanrebel** [comment]
Works like a charm. Thanks a lot!
