### ISSUE TITLE
Problem creating a new WorkSpace

### ISSUE THREAD

**Issue by deckard86** [mirumee/overv.io-beta#374]
Hello guys,

I'm having problems creating new workspaces. I've create a new repository en Git-Hub named gp-dev. This repo is empty. I've created it for trying this ¿bug?

Ok, when I select the repo in workspace creation, I obtain this screen an nothing happens

![overvio](https://cloud.githubusercontent.com/assets/6379597/5332202/2407b6f2-7e4e-11e4-9c6a-aaa8df05d82d.png)

Regards :)

**Comment by mirekm** [comment]
Thanks for the feedback Ángel. We're looking into it.

**Comment by deckard86** [comment]
:+1:

**Comment by mirekm** [comment]
Hi Ángel,

The issue seems to be resolved. Thanks for your feedback, it's highly appreciated!

**Comment by deckard86** [comment]
Yes, now it works properly :)
