### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by ColinAvrech** [mirumee/overv.io-beta#383]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

Not sure what all you want here but I'm a producer on a student game team over at Digipen. I'm trying out code review tools to see what to use for my team and need an account that supports up to ten users. We currently have a basic 2D platformer where you play as a lonely fireball intent on ARBOR GENECIDE. As you wage your ill intentioned war BURNING innocent trees you progress through the levels until you meet your maker.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/dashboard/

Godspeed! :zap:
