### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by abargmann** [mirumee/overv.io-beta#393]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

Few notes about me: 
- currently use github issues / pull requests + waffle.io
- i work with a product team of 3-5 people, our full product + engineering group is 19. 
- we now have 5 repos that are in production development

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/dashboard/

Godspeed! :zap:
