### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by roadsideseb** [mirumee/overv.io-beta#4]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

I also want to say, that I am so excited about exploring your great work, that I feel like a 5-year-old with his head stuck in a triple fudge chocolate cake :smile: Thanks!

**Comment by patrys** [comment]
Best issue ever and you are more than welcome! Please let other Tangent members know we're inviting.
https://overv.io/login/
