### ISSUE TITLE
Pretty please - for real

### ISSUE THREAD

**Issue by damianesteban** [mirumee/overv.io-beta#412]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

I look forward to beta-testing :)

-Damian

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:

**Comment by damianesteban** [comment]
I changed my GitHub username from _estebanrules_ to _damianesteban_ two
days ago.  I activated my account but now I'm unable to login.

Thank you.

On Mon, Mar 16, 2015 at 2:17 PM, Mirek Mencel notifications@github.com
wrote:

> Closed #412 https://github.com/mirumee/overv.io-beta/issues/412.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mirumee/overv.io-beta/issues/412#event-255891667.

## 

[image: --]
Damian Esteban
[image: https://]about.me/DamianEsteban
https://about.me/DamianEsteban?promo=email_sig
