### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by gump** [mirumee/overv.io-beta#45]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

Hey guys,
Michal here - we used to work at Tangent together. Now I moved on, seen this new sexy thing you're working on and thought I could try it out with my team. We work on artfinder.com and an issue management like overv.io is exactly what we've been looking for. Sign me up pretty please!
Michal aka Gump

**Comment by mirekm** [comment]
Hi Michal,

Small and medium teams feedback is what we're looking for!
You're good  to go: https://overv.io/login/

btw. https://www.artfinder.com looks really cool! Congrats!

**Comment by gump** [comment]
Hi @mirekm 
Thanks for that! The board looks sweeeeet!

If I want to add my team mates - do I need to ask you to let them in? I cannot work that out from the UI :( Their github usernames are: @dominicglenn and @arekartfinder

Thanks!
Michal

**Comment by mirekm** [comment]
Still work in progress but thanks! :)
I've just white-listed both.
