### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by alecoot** [mirumee/overv.io-beta#457]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

In addition to being eternally grateful for being part of the closed beta, here's a video for your time: https://www.youtube.com/watch?v=O7D-1RG-VRk

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/dashboard/

Godspeed! :zap:
