### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by wenzowski** [mirumee/overv.io-beta#463]
Sweet application process. :dog: food :+1: 

Currently using issues for project management of Dialog, my latest startup. This looks like it would be incredibly useful to us.

Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
