### ISSUE TITLE
Add edit/close/add to milestone menu to "large" ticket view

### ISSUE THREAD

**Issue by gump** [mirumee/overv.io-beta#47]
When one creates a ticket and forgets to select a milestone - then quickly clicks on the very useful notification popup. This brings up the popup / large ticket view, which is missing an essential functionality - the little menu that would allow setting a milestone.

Otherwise - I need to find the ticket in a workspace which is really time consuming

![screen_shot_2014-03-27_at_18_12_57](https://cloud.githubusercontent.com/assets/528842/2541316/0c78e2c6-b5dc-11e3-8522-4afca3fb8047.jpg)

![artfinder_workspace](https://cloud.githubusercontent.com/assets/528842/2541317/0e7aec5e-b5dc-11e3-9d10-2f64fc070523.jpg)

**Comment by mirekm** [comment]
:+1:
