### ISSUE TITLE
Still syncing after 1 hour

### ISSUE THREAD

**Issue by pathikrit** [mirumee/overv.io-beta#473]
https://overv.io/workspace/pathikrit/lovely-wasp/

**Comment by mirekm** [comment]
Thank you for the feedback. We're looking into it.

**Comment by mirekm** [comment]
Please have a look again. In general, syncing process is quick but we're still working on the performance of the queue behind. We hopefully have this fully resolved with the next release.

**Comment by pathikrit** [comment]
still syncing

**Comment by mirekm** [comment]
Sorry to hear it. We've just released a minor update fixing some small issues with data handling during the syncing process and we believe it should also help in your case. It would be great if you could check again and let us know.

**Comment by pathikrit** [comment]
still syncing

**Comment by mirekm** [comment]
![Oh noes!](http://i.giphy.com/8VQ75D0ZA1m2k.gif)

It's quite strange since our all testing repositories are working fine. As long as we're still investigating it there's another patch in place which should finally fix it for you. :see_no_evil: 
Thanks for you patience and keep us posted!

**Comment by pathikrit** [comment]
It works now! Thanks!
