### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by nathanielks** [mirumee/overv.io-beta#479]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

Also: here's a gif. Happy St. Patricks day :)

![giphy-11](https://cloud.githubusercontent.com/assets/314009/6694683/d42385e4-cca9-11e4-85ff-2c43a37de02a.gif)

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap::four_leaf_clover: :smile_cat:

**Comment by nathanielks** [comment]
![giphy-12](https://cloud.githubusercontent.com/assets/314009/6700131/708aac82-ccd7-11e4-988c-3df177269df0.gif)
