### ISSUE TITLE
support for private repos belonging to organisation

### ISSUE THREAD

**Issue by geoffliddiard** [mirumee/overv.io-beta#487]
getting 404 errors when trying to add private repositories from an organisation that I am an admin of. All our repos are private, so this is a bit of a roadblock for us at the moment.

**Comment by mirekm** [comment]
Hey Geoff,

Thanks for the feedback — private repositories should work as well as the public ones.
First of all, do you see your private repo(s) in the **Select your repositories** list in _Create new project_ form?

**Comment by geoffliddiard** [comment]
My bad - looks like I hadn't granted permissions successfully, all good now thanks

**Comment by mirekm** [comment]
No worries. Don't hesitate to visit us here again if anything else will pop out! :+1:
