### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by Masstronaut** [mirumee/overv.io-beta#488]
I'm interested in checking out your tools. I run a 10-man team currently, and we don't really have a good solution for project management tools. We use slack to communicate, but when we had an active trello I found that nobody was really using it, which defeats the purpose of the tool. My team is very social, and I think the active social aspects of your toolset would help interest us and keep us using the tools so they remain effective.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/
You can nominate up to 5 co-pilots using the invitations you can find in the Settings panel.

For regular updates follow us on https://twitter.com/overvio

Godspeed! :zap:
