### ISSUE TITLE
Editing an issue that has a PR attached causes funny issues

### ISSUE THREAD

**Issue by gump** [mirumee/overv.io-beta#49]
For an issue that's got a PR attached - a lovely PR icon is displayed, however when you go an edit such issue in the editor - it saves a bit of HTML into the issue's title:

1) Find an ticket that's a PR ticket
![screen_shot_2014-04-07_at_18_17_19](https://cloud.githubusercontent.com/assets/528842/2634274/b707a44e-be78-11e3-9df6-a990eb8b0485.jpg)

2) Edit the ticket - HTML of the icon gets inserted into the text field
![screen shot 2014-04-07 at 18 18 15](https://cloud.githubusercontent.com/assets/528842/2634289/e5a9212e-be78-11e3-987f-f9ca77aa03f4.png)

3) Save (of course one was not expecting this to happen) and tada!!!
![screen_shot_2014-04-07_at_18_11_36](https://cloud.githubusercontent.com/assets/528842/2634294/f96dd7b8-be78-11e3-92ca-7e5ae3c6e16e.jpg)

**Comment by mirekm** [comment]
:+1:
