### ISSUE TITLE
Overlapping elements

### ISSUE THREAD

**Issue by degiorgig** [mirumee/overv.io-beta#496]
Hi!

The preview switch is overlapping the cancel button.

![overlap](https://cloud.githubusercontent.com/assets/73665/6960722/39f54e8e-d925-11e4-9f88-6e7d658e90c8.png)

Cheers
L.

**Comment by mirekm** [comment]
Thanks for the feedback Giovanni. It requires fixing nonetheless but what screen resolution are you working on?

**Comment by degiorgig** [comment]
Hi Mirek,
I'm on 1366x768 pixel resolution, definitely not the biggest on the market.

Cheers
G.
