### ISSUE TITLE
Pretty please ;)

### ISSUE THREAD

**Issue by HWideman** [mirumee/overv.io-beta#499]
I am a student of computer science based in Raleigh, NC, USA. Sometimes, while working on class projects and personal endeavors I have found github to be clunky or non-intuitive. While this has led me to learn more about github, I would love to try your web app and see if it will help me manage and work in a more efficient manner. Also, you guys' design/style fucking rocks and is definitely an inspiration for a webpage I am working on.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/
You can nominate up to 3 co-pilots using the invitations you can find in the Settings panel.

For regular updates follow us on https://twitter.com/overvio

Godspeed! :zap:
