### ISSUE TITLE
Cannot click menu above certain cursor position (odd one)

### ISSUE THREAD

**Issue by gump** [mirumee/overv.io-beta#50]
In Chrome > Workspace view:

1) Scroll down the issue list quite a bit so that the nav shrinks (it has to be far down the page)
2) Scroll back up just a little bit so that the issue's menu/assign/play icons are just below the top column heading bar
3) Clicking on any of the "clickable" elements does not result in the expected way

Elements roughly 0-150px below the top bar are not clickable, the rest is clickable just fine.

![artfinder_workspace 2](https://cloud.githubusercontent.com/assets/528842/2634684/d4581944-be7c-11e3-84ef-59655bb3c76b.jpg)

**Comment by mirekm** [comment]
Thanks, it's related to the sticky headers. It should be fixed with the next patch release this week.

**Comment by gump** [comment]
:+1: Thanks @mirekm that's great!
