### ISSUE TITLE
Unable to create first project

### ISSUE THREAD

**Issue by smarterclayton** [mirumee/overv.io-beta#507]
Trying out the private beta - I created a new project and selected the "openshift/origin" repo.  When I try to create the project from it, the create button accepts the click, cycles for a bit, but then goes back to "create" and nothing is created.  In the javascript console I see:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
https://overv.io/api/workspaces/ 
```

**Comment by mirekm** [comment]
Thank you for the feedback and sorry for a late response. Did you eventually manage to create your project?

**Comment by smarterclayton** [comment]
I have not tried recently, but I was not able to import it.

**Comment by mirekm** [comment]
Sorry to hear that. We had couple of updates since then addressing improvements in import process so the problem should be hopefully fixed. It would be great if you could try it out again and let us know.

Kind regards,
Mirek

**Comment by smarterclayton** [comment]
When I try to create, I see this:

```
POST https://overv.io/api/workspaces/
{"name":"OpenShift","repositories":[{"owner":"openshift","name":"origin"}],"columns":["open","in progress","closed","archive"]}
404 Not Found
```

----- Original Message -----

**Comment by mirekm** [comment]
Thanks for providing this feedback Clayton. I believe I've discovered the reason — your username hasn't been downloaded with other assignee names for openshift/origin repo. I've deployed a fix already and it should hopefully work now. Once again my apologies for the inconvenience.
Let us know if the above helped and be sure to bug us about any other features you'd like to see implemented or improved!

**Comment by smarterclayton** [comment]
Worked, thanks!

----- Original Message -----
