### ISSUE TITLE
Front-end performance problems

### ISSUE THREAD

**Issue by ehausen** [mirumee/overv.io-beta#509]
First of all a thankyou: Amazing work guys! I have spending last couple of weeks searching for a supplement to Githubs limited interface that would still support basic features of Github and allow Github to be used also. I think I have found it. Thank you!

The interface seemed to be a bit sluggish. I didn't have time to make so close analysis but I think just changing some CSS selectors to GPU accelerated ones would make the experience silky smooth. :)

These are golden: 
http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/
https://www.youtube.com/watch?v=n8ep4leoN9A

How is your time? Would you like me to take a look at the front-end fine tuning? I'm quite busy with the launch of our product, but I think I might be able to make some time, if needed.

**Comment by mirekm** [comment]
Thank you Erik! Good feedback. Silky smooth experience is absolutely on our list of goals and we're currently working on the performance issues. Please feel free to share your findings, thoughts and suggestions.

**Comment by ehausen** [comment]
I'll be back with more details, but I think changing some _translate(_ to _translate3d(_ should trigger GPU acceleration.  

I was also thinking that maybe the animation that "sucks" in the header when scrolled down maybe just makes it feel a bit  "janky".

http://wesleyhales.com/blog/2013/10/26/Jank-Busting-Apples-Home-Page/
