### ISSUE TITLE
Github now have added more granular permissions, at least for organizations

### ISSUE THREAD

**Issue by ehausen** [mirumee/overv.io-beta#511]
https://developer.github.com/changes/2015-06-24-api-enhancements-for-working-with-organization-permissions/

**Comment by rjmackay** [comment]
Any chance of using much less all-consuming permissions? "This application will be able to read and write all public and private repository data." scares me a lot when I'm just trying an app out.

**Comment by mirekm** [comment]
Thanks for the feedback. We're aware of the importance of this change — it's among priorities at the moment and should be available soon.

**Comment by mirekm** [comment]
You can opt now for just public repositories when logging into Overv.io (https://overv.io/login/). We hope this solves the problem for anyone just trying the app out.
