### ISSUE TITLE
UI: The header bar

### ISSUE THREAD

**Issue by ehausen** [mirumee/overv.io-beta#513]
Right now the header bar autohides when user stops scrolling down. This gives a bit jumpy effect as the hiding/sliding away happens after user stops scrolling and not while user is scrolling.

I suggest:
- Change the sliding behaviour so that the header bar slides away while scrolling, like with http://wicky.nillia.ms/headroom.js/

Maybe even better?
- Get rid of the whole header bar by putting the controls in the sidebar, there is space..

What do you think?

**Comment by mirekm** [comment]
Good point regarding the animation — we will fix it.
I think moving everything to the sidebar is not an option at least for now since there are some other plans regarding this space. The plan is to allow saving filters there (so they can be quickly available from the sidebar as another views).

**Comment by ehausen** [comment]
It feels like you changed something! Looks good!

I noticed some controls to top right are left behind.

<img width="151" alt="screen shot 2015-07-12 at 19 06 15" src="https://cloud.githubusercontent.com/assets/6204129/8638893/38475f52-28c9-11e5-8243-f7e271693b3a.png">

**Comment by mirekm** [comment]
Thanks. Fixed.

**Comment by mirekm** [comment]
A quick update — we've found couple of other problems regarding performance (mainly with regards to scrolling) and we're working on it.
