### ISSUE TITLE
Missing 'expand column' toggle

### ISSUE THREAD

**Issue by ehausen** [mirumee/overv.io-beta#514]
Hello!

I can't find any way of expanding my collapsed columns. I not so sure, but I think the toggle was there before, but just can't find it now. Am I blind? :confused: 

<img width="330" alt="screen shot 2015-07-12 at 17 00 53" src="https://cloud.githubusercontent.com/assets/6204129/8638309/abb814c0-28b7-11e5-8c36-d49c8a1f1303.png">

**Comment by mirekm** [comment]
Hi Erik,

No you're not, I've just hot-fixed it. It was a regression bug introduced by the first batch of performance related changes. Sorry for that and thank you for another great feedback.

**Comment by ehausen** [comment]
Working!
