### ISSUE TITLE
Long labels names do not fit to screen in card view dropdown

### ISSUE THREAD

**Issue by ehausen** [mirumee/overv.io-beta#520]
<img width="296" alt="screen shot 2015-07-29 at 15 00 29" src="https://cloud.githubusercontent.com/assets/6204129/8956882/a9779bf6-3602-11e5-945a-916df66325cf.png">

**Comment by mirekm** [comment]
Thanks for filing this issue. It's been (at least) partially fixed with the latest release and new label/assignee/milestone selectors.
