### ISSUE TITLE
GitHub Enterprise

### ISSUE THREAD

**Issue by divmain** [mirumee/overv.io-beta#523]
Hey guys,

Liking this app very much!  I work with the core-web team of a Fortune 5 company, and was wondering if you all support GitHub Enterprise / private installations?  We've evaluated ZenHub and trying waffle.io now, but would love to put a bug in my manager's ear about Overv.io if GHE is supported.

Thanks!

**Comment by mirekm** [comment]
Hey Dale,

Thank you for writing to us and sharing your kind feedback! We're currently working on Overv.io Enterprise version, could you please write me on my email for more details?

**Comment by divmain** [comment]
Thanks, will do!
