### ISSUE TITLE
Mobile app opens just overv.io web page when trying to log in

### ISSUE THREAD

**Issue by ehausen** [mirumee/overv.io-beta#525]
I can't log int to mobile app. Every time I click the login with github button in the apps first screen I get redirected to the desktop version of over.io on my phones web browser. Logging out of that desktop mode and trying to log in with the app again doesn't help.

**Comment by ehausen** [comment]
Still same problem.
- Mobile app: tap on authorize with github
  --> redirected to github authentication in phone browser
- tap on authentication
  --> redirected to overv.io desktop page. Stays there
- When going to mobile app, it still presents the auhtentication page

The app was working earlier

@mirekm, can I help somehow?

**Comment by ehausen** [comment]
Reinstall of the app did not help

**Comment by mirekm** [comment]
Hi Erik, there's an issue introduced by one of the last API releases. Sorry for the trouble - we will try to fix it as soon as possible.
