### ISSUE TITLE
Android app: handler for github issue links

### ISSUE THREAD

**Issue by mrenvoize** [mirumee/overv.io-beta#527]
Would be nice to have a handler for when a github issue url is clicked.  The now open source github android client does this so it might be a good place to see how it's done ;) ForkHub.

**Comment by mirekm** [comment]
Thanks Martin. It's been on our internal list for a while and the good news is that we're already working on this! Stay tuned.

**Comment by mrenvoize** [comment]
Great news,  would contribute out myself if I could. 

So happy to see this project :-)

**Comment by mirekm** [comment]
Thank you for the feedback guys. GitHub links handling is now available. Please have a look at the newest version —  https://play.google.com/store/apps/details?id=io.overv

**Comment by mrenvoize** [comment]
Sorry to report guys, but this latest android app update seems to have broken the app for me.

I now get a force close the moment I attempt to open the app.. If I can help testing a fix,  shout.

I'm on a Sony Xperia Z3 compact, with android 5.1.1

**Comment by mrenvoize** [comment]
Looking good again now, great work acting so quickly

**Comment by mirekm** [comment]
:+1:
