### ISSUE TITLE
Milestone Popover seems to get stuck from time to time!

### ISSUE THREAD

**Issue by DS-Matt** [mirumee/overv.io-beta#528]
Hello -

I've noticed when I hover over the github milestone the back popover seems to get displayed and sometimes get stuck (requiring me to refresh the page to get rid of the popover displayed).  Unfortunately after refreshing last time I it isn't doing it so I can't recreate it right now for a screen grab - but as soon as it happens again I'll make a screen grab.

**Comment by mirekm** [comment]
Fixed with new milestone's deatils handling (only browser's tooltips and details view).
Related to #529
