### ISSUE TITLE
Text sometimes goes outside of milestone description popover

### ISSUE THREAD

**Issue by DS-Matt** [mirumee/overv.io-beta#529]
![popover text outside of popover background](https://cloud.githubusercontent.com/assets/1852169/12732953/d5058bfc-c8ec-11e5-8a3d-6429f3c01436.png)

**Comment by mirekm** [comment]
Thank you for the feedback.

I believe this popover is already a bit redundant and doesn't bring that much of a value anymore. It seems to contain two important details that aren't communicated anywhere else at the moment: 1) the exact due date which can be just a standard tooltip on inline _Due on_ section (just after name in milestone's header) and 2) open/closed ratio (ie. 3 open / 30 closed) which can be in turn a standard tooltip of a milestone's name. The only question mark would be around the description which in your case seems to be quite in depth and I suppose important to have somewhere available in the UI.

**Comment by DS-Matt** [comment]
Hi @mirekm -

Thanks for the quick response.  I agree the popover is not necessary - because I can click on the hamburger icon next to the Milestone name and then click "edit" to see the description (you could add a "View" button which would be great - you could also allow it to then view the description in Markdown (we write specifications for each milestone in Markdown -- this came from us using Jira/Confluence for documentation).  That's why my descriptions are long - we define a new feature or spec for a project as milestone and write the requirements in a word processor/Markdown editor then paste them into the Github milestones - so it would be AWESOME if you could support a "view" modal similar to the "Edit" modal but displaying the information of the Milestone (and supporting markdown)!  

Thanks!

**Comment by mirekm** [comment]
Description is now available only in details modal — under title's click or from milestone's menu. It supports markdown as well. :zap:

**Comment by DS-Matt** [comment]
You guys (or gals) are awesome!  This looks so good and seems much more functional! Thanks!
