### ISSUE TITLE
Viewing a single issue does not work - the windows stays grayed out / disabled

### ISSUE THREAD

**Issue by borekb** [mirumee/overv.io-beta#542]
When I click on a title of a single issue, it should open a popup with the issue details. Instead, this happens:

![image](https://cloud.githubusercontent.com/assets/101152/14106522/f95d7298-f5b1-11e5-9e23-28742753973b.png)

This happens to me in both Firefox 46.0b5 and Chrome 49.

**Comment by borekb** [comment]
The gear icon next to the checkmark in the top left corner keeps spinning BTW, if that's any clue.

**Comment by mirumeedev** [comment]
The trouble is that we still can't reproduce it. Do you mind to have a look into your browser's console and see if there are any errors?

**Comment by mirekm** [comment]
The trouble is that we still can't reproduce it. Do you mind to have a look into your browser's console and see if there are any errors?

**Comment by borekb** [comment]
There's one error:

```
build.fb2bf3fa20d72cd9.js:41 Uncaught TypeError: Cannot read property 'getName' of undefined
```

**Comment by borekb** [comment]
In Firefox, it started working. In Chrome, it still doesn't. Maybe some caching issues, I don't know.

**Comment by mirekm** [comment]
Thank you for additional information Borek. We've just deployed a possible fix. Please let us know if the problem still exists.

**Comment by borekb** [comment]
Strangely enough, it works fine on one of our boards and still fails on another. The only difference I can tell is the number of issues – the board where it works has relatively small amount of issues, the board where it fails is bigger.

Specifically, it works on https://overv.io/workspace/borekb/delightful-shrew/board/ (private repo) and does not work on https://overv.io/workspace/JanVoracek/cautious-tarsier/ (private repo too).

**Comment by mirekm** [comment]
Strange indeed. We still struggle to reproduce the problem. Could you please send us the (unfolded) error stack from console?

**Comment by borekb** [comment]
Here it is:

```
build.6bedf41a70e2c8e3.js:41 Uncaught TypeError: Cannot read property 'getName' of undefined(anonymous function) @ build.6bedf41a70e2c8e3.js:41
at @ build.6bedf41a70e2c8e3.js:26
Zi @ build.6bedf41a70e2c8e3.js:27
n.getStatusLabels @ build.6bedf41a70e2c8e3.js:41
t.initialize @ build.6bedf41a70e2c8e3.js:214
t.View @ build.6bedf41a70e2c8e3.js:35
t @ build.6bedf41a70e2c8e3.js:45
t @ build.6bedf41a70e2c8e3.js:78
t @ build.6bedf41a70e2c8e3.js:78
t @ build.6bedf41a70e2c8e3.js:78
t @ build.6bedf41a70e2c8e3.js:160
t @ build.6bedf41a70e2c8e3.js:160
t @ build.6bedf41a70e2c8e3.js:213
t @ build.6bedf41a70e2c8e3.js:213
t @ build.6bedf41a70e2c8e3.js:213
t @ build.6bedf41a70e2c8e3.js:214
t.build @ build.6bedf41a70e2c8e3.js:212
t.render @ build.6bedf41a70e2c8e3.js:78
t.buildHelp @ build.6bedf41a70e2c8e3.js:212
t.build @ build.6bedf41a70e2c8e3.js:159
t.build @ build.6bedf41a70e2c8e3.js:212
t.render @ build.6bedf41a70e2c8e3.js:78
t.render @ build.6bedf41a70e2c8e3.js:79
t.onLoad @ build.6bedf41a70e2c8e3.js:79
t._success @ build.6bedf41a70e2c8e3.js:79
(anonymous function) @ build.6bedf41a70e2c8e3.js:78
u @ build.6bedf41a70e2c8e3.js:24
p.add @ build.6bedf41a70e2c8e3.js:24
t.load @ build.6bedf41a70e2c8e3.js:79
t.initialize @ build.6bedf41a70e2c8e3.js:79
t.initialize @ build.6bedf41a70e2c8e3.js:159
t.View @ build.6bedf41a70e2c8e3.js:35
t @ build.6bedf41a70e2c8e3.js:45
t @ build.6bedf41a70e2c8e3.js:78
t @ build.6bedf41a70e2c8e3.js:78
t @ build.6bedf41a70e2c8e3.js:78
t @ build.6bedf41a70e2c8e3.js:79
t @ build.6bedf41a70e2c8e3.js:159
t @ build.6bedf41a70e2c8e3.js:212
t.showTicket @ build.6bedf41a70e2c8e3.js:211
t.navigate @ build.6bedf41a70e2c8e3.js:211
(anonymous function) @ build.6bedf41a70e2c8e3.js:26
(anonymous function) @ build.6bedf41a70e2c8e3.js:26
```

**Comment by borekb** [comment]
@mirekm I've added you to the VP repo so that you can try the board yourself, possibly with a non-minified JS. https://overv.io/workspace/JanVoracek/cautious-tarsier

**Comment by mirekm** [comment]
Once again thank you for helping us resolve this issue  @borekb. The problem lied in removed `archive` label. The appropriate fix addressing this issue has been deployed. `Archive` label is used for marking finalized and closed issues that no longer need to appear in overv.io.

**Comment by borekb** [comment]
Thank you!

BTW I was always wondering about the `Archive` label. We usually don't want to worry about the closed issues anymore so manually going through them and assigning an `Archive` label isn't something we would be keen to do. I think overv.io already limits the number of displayed closed issues to something reasonable, which seems perfectly fine to us.
