### ISSUE TITLE
Issue author (reporter) is incorrect

### ISSUE THREAD

**Issue by borekb** [mirumee/overv.io-beta#543]
Overv.io:

![image](https://cloud.githubusercontent.com/assets/101152/14177256/b9ae86c8-f755-11e5-8ce2-4965405e14e2.png)

GitHub:

![image](https://cloud.githubusercontent.com/assets/101152/14177275/cdacc004-f755-11e5-8f71-ff7f32ea4179.png)

**Comment by mirekm** [comment]
Thank you @borekb. Fixed.
