### ISSUE TITLE
Comments don't load

### ISSUE THREAD

**Issue by borekb** [mirumee/overv.io-beta#544]
Possible JS bug: comments don't load:

![image](https://cloud.githubusercontent.com/assets/101152/14200762/7b866ff8-f7ed-11e5-830c-7a51d12fb6d6.png)

From the Firefox dev console:

```
TypeError: o is undefined
w</t.prototype.build/n</<()
 build.3e9a3f60603c8d8c.js:214
w</t.prototype.build()
 build.3e9a3f60603c8d8c.js:214
f</t.prototype.render()
 build.3e9a3f60603c8d8c.js:78
f</t.prototype._renderChild()
 build.3e9a3f60603c8d8c.js:78
d</t.prototype._renderAsync/</</<()
 build.3e9a3f60603c8d8c.js:78
b/<()
 build.3e9a3f60603c8d8c.js:35
i()
 build.3e9a3f60603c8d8c.js:35
i/<()
 build.3e9a3f60603c8d8c.js:35
c/<()
 build.3e9a3f60603c8d8c.js:35
```

**Comment by mirumeedev** [comment]
Sorry for a delay but we again struggle with reproducing this issue. You seem to posses some exquisite testing and overv.io-breaking skills  :tophat: :+1:

**Comment by mirekm** [comment]
Sorry for a delay but we again struggle with reproducing this issue. You seem to posses some exquisite testing and overv.io-breaking skills  :tophat: :+1:

**Comment by mirekm** [comment]
The moment I wrote it I managed to reproduce it :smile: The appropriate fix will be available online soon. Thanks for the feedback @borekb !

**Comment by borekb** [comment]
No problem, I enjoyed the hat :)

**Comment by mirekm** [comment]
Great, our fix is ready for testing then!
