### ISSUE TITLE
Milestone marked as past due date even if it isn't

### ISSUE THREAD

**Issue by borekb** [mirumee/overv.io-beta#545]
We have a milestone that ends today. GitHub is perfectly fine with this (we still have a couple of hours to make it) but overv.io complains in the _Milestones_ panel - "Past due by a day".

My guess is that when overv.io sees 6 Apr 2016, it takes it as 6 Apr 2016 **0:00** while it should use **23:59** instead.

**Comment by mirekm** [comment]
:+1: Your were right.  Fixed.
