### ISSUE TITLE
Option to disable "big avatars" layout

### ISSUE THREAD

**Issue by borekb** [mirumee/overv.io-beta#547]
A couple of weeks back, overv.io deployed a new layout that uses big user avatars as the main UI element on every card:

![image](https://cloud.githubusercontent.com/assets/101152/14377462/0123810a-fd70-11e5-9b0c-d45fdcbb95de.png)

We still much prefer the "compact" style which overv.io used before and still uses on narrower screens:

![image](https://cloud.githubusercontent.com/assets/101152/14377476/10bf8942-fd70-11e5-87be-91751915f094.png)

Would it be possible to add an option to force this layout even on wider screens? Big user avatars are not that useful for us.

**Comment by mirekm** [comment]
Eventually we decided to give it a go! Please have a look at the _Advanced_ tab of your workspace's settings and thanks for the patience!

**Comment by borekb** [comment]
@mirekm Very cool! The layout is great but perhaps this should be a user setting (_Settings > General/View_), not a board setting.
