### ISSUE TITLE
Issue closed via a merged PR doesn't remove the progress label

### ISSUE THREAD

**Issue by borekb** [mirumee/overv.io-beta#552]
We have four columns, `open`, `in progress`, `in review` and `closed`. The issue is typically in the third column, awaiting review on a related PR. When the PR is reviewed and merged into master, the issue correctly moves to the closed state but the `in review` label is still attached on it. It should be removed as well.

**Comment by TiSiE** [comment]
The same happens to issues closed via commit message. (i.e. "Fix|Close issuenumber")

**Comment by mirekm** [comment]
Thank you for the feedback. This issue should be fixed with the latest release.
