### ISSUE TITLE
Layout bug

### ISSUE THREAD

**Issue by borekb** [mirumee/overv.io-beta#553]
This doesn't seem right:

![image](https://cloud.githubusercontent.com/assets/101152/14703664/62fa848c-07b1-11e6-86f6-da16d4aaf8b2.png)

The "in review" tickets overflow to the CLOSED column.

**Comment by patrys** [comment]
Wow, that's quite a long name for a test :wink: 

We'll try to crop it so it does not make the column extra wide. Thanks for the report! :+1:

**Comment by borekb** [comment]
I'm sure we have even longer ones :) Thanks for looking into it.

**Comment by mirekm** [comment]
Ready for testing ;)

**Comment by borekb** [comment]
Works great. :+1:
