### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by chriswaalberg** [mirumee/overv.io-beta#58]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

We could really use this for one of our projects, starting in a couple of weeks.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
