### ISSUE TITLE
Drag and drop issues

### ISSUE THREAD

**Issue by timanrebel** [mirumee/overv.io-beta#59]
I keep trying to drag and drop issues. To change the order inside a filter or between filters (Drag issues from in progress to finished for example). It would be really nice if that would be possible.

**Comment by mirekm** [comment]
Thank you for the feedback Timan, highly appreciated.

I'm not sure if that's the problem (and I know it might not be the easiest experience yet) but you can drag and drop issues grabbing them by a title. At the moment title has two actions associated to it — details view (when you single click on it), and drag and drop when you drag it.

You should be able to change order/priority within a single column. Currently, if you want to drag into a different column we effectively suggest a minimal subsets of changes required for the ticket to show up in a particular column.

If you have any other suggestions don't hesitate to let me know.

**Comment by timanrebel** [comment]
Thanks for the quick reply. Somehow never tried the title, only the box. Thanks! This is what I was looking for
