### ISSUE TITLE
Commits visible in issues on Overv.io

### ISSUE THREAD

**Issue by timanrebel** [mirumee/overv.io-beta#65]
Hey guys,

I'll just keep sharing my feedback.. What I really liked about my integration between PivotalTracker and Github was that all commits were visible as comments. (Github shows commits even as commits instead of comments).

Is it possible or would it be a nice enhancement to show commits in Overv.io as well? So I can either lookup my own commits, or do code reviews on commits from my colleagues.

**Comment by mirekm** [comment]
Thanks for sharing Timan. This is definitely a good point and we will look into it as soon as possible. Will keep you posted.

**Comment by timanrebel** [comment]
![screen shot 2014-05-05 at 13 30 28](https://cloud.githubusercontent.com/assets/1079937/2877327/e533623c-d448-11e3-8f4b-193fe47dd590.png)

Thank you very much for implementing this! 

Maybe one small improvement: Could you also add the commit message like on Github?

![screen shot 2014-05-05 at 13 35 05](https://cloud.githubusercontent.com/assets/1079937/2877342/5563e02c-d449-11e3-9282-514958d1940a.png)
