### ISSUE TITLE
Possible to add extra statuses?

### ISSUE THREAD

**Issue by timanrebel** [mirumee/overv.io-beta#68]
Is it possible to add extra statuses except open, in progress and finished? Would like to have an extra column 'tested'. Can add the column with a filter on the tag 'tested', but I cannot remove the status 'finished'. Or are the statuses open, in progress and finished a kind of special Github tags?

**Comment by timanrebel** [comment]
Working with Github Issues and Overv.io for another couple of days, I learned that you need to close issues before milestones are marked as complete. Closing a ticket would be the same as marking them as complete, but I can not add a column 'closed'

So maybe this is a separate request, or the same, but I would also like to add a column with all 'closed' issues

**Comment by mirekm** [comment]
It took a while but we've finally made our minds up.  Overv.io will support custom statuses soon.

**Comment by mirekm** [comment]
You can now specify your own flow with as many columns as you need. Check your project settings! :raised_hands:
