### ISSUE TITLE
Can not find how to add comments or change estimation in compact issue view

### ISSUE THREAD

**Issue by timanrebel** [mirumee/overv.io-beta#70]
I've been looking how to change the estimation of a ticket, or how to add a comment to a ticket for the whole day. I really thought that you guys must have changed the UI!

Luckily I found that you can change the estimate or add comments only in the big issue view, not in the compact issue view. But for me it was quite confusing. Maybe add 2 small buttons in the compact view on hover, just like the edit button next to the time

(And while writing this issue, I found that you can indeed also do it on the detail view, so maybe it is just me :))

**Comment by mirekm** [comment]
Fixed with #71
