### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by upworthymatic** [mirumee/overv.io-beta#74]
![image](https://cloud.githubusercontent.com/assets/5035041/2867818/06bb8100-d23c-11e3-927e-36dcf44e5719.png)

We'd like to try this! We have many repos and would really love to experiment with this workspace based approach.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
