### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by fmr** [mirumee/overv.io-beta#8]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

P.S.
I saw @a-musing-moose playing with it and it looks pretty impressive so far. I'd like to join in the fun!

**Comment by mirekm** [comment]
You're welcome! Thanks for joining.
