### ISSUE TITLE
Pretty please

### ISSUE THREAD

**Issue by Dgigiu** [mirumee/overv.io-beta#84]
Please recognize my effort that consists mostly of filling this form and find me worthy of joining the private beta. I hereby offer my solemn vow to file all issues I encounter, share my experience when asked to and sport a big smile for the rest of the day.

How did I find you? Well, Timan Rebel showed me your product and it was love at first commit. Looking forward to start using it!

Thanks! Cheers,
Miguel

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
