### ISSUE TITLE
Order is not preserved in open tickets

### ISSUE THREAD

**Issue by timanrebel** [mirumee/overv.io-beta#88]
It took me a while to realise, but the order of issues is not preserved in the open ticket column (haven't tried it with the others).

The issues stay at the right order for a while and then all of a sudden they are not. It seems to happen in the background, because I haven't caught overv.io changing the order :)

**Comment by mirekm** [comment]
Thanks @timanrebel Great feedback again. Reordering might change completely soon. We will roll out the next important milestone first (it's nearly ready) and once in place we will shed some light about the prioritization direction we want to follow (which might be close to what we have at the moment but we believe is a better way to work).

**Comment by timanrebel** [comment]
Great! Keep me in the loop. Am using Overv.io daily at the moment and am really liking it.

**Comment by mirekm** [comment]
Thank you for feedback and patience. Drag and drop prioritizing should work as expected now.
