### ISSUE TITLE
Hi we're WappZapp !

### ISSUE THREAD

**Issue by PierreGUI** [mirumee/overv.io-beta#90]
Hey there !
As a front-end developer at WappZapp(.tv) startup (in the Netherlands), I was looking for a better tool to work with the team. Many websites, many kanban/lean/agile/boards stuff etc... But nothing special... and then I found you !
PLEASE let me give a try to Overv, looks so great ! Reviewing (again) all available online tools, I always come back to your website (awesome btw).

Can't wait to have news from you guys
Cheers
Pierre

**Comment by timanrebel** [comment]
Hope it is okay I actively promote Overv.io in the Dutch startup scene ;)

**Comment by mirekm** [comment]
Thanks for applying @PierreGUI !
@timanrebel Of course it is! Awesome.

We will release another batch of invitations any time soon once the latest, important milestone hits the servers. Keep calm and stay tuned.

**Comment by PierreGUI** [comment]
Cool ! Thank you

**Comment by mirekm** [comment]
Just btw. we're also running http://twitter.com/overvio account in case you want to stay in touch with recent changes etc.

**Comment by mirekm** [comment]
Thank you for your application, pilot. You are to immediately report to your battlestation: https://overv.io/login/

Godspeed! :zap:
